### ISSUE TITLE
Provide ability to order of Sheet Columns while writing to sheet 

### ISSUE THREAD

**Issue by millij** [millij/poi-object-mapper#12]
Currently, the columns are written no specific order.
Add support to provide the Order of the columns while writing.

**Comment by oshuk1** [comment]
Is it done or is there any other way to achieve the ordering of columns in sheet?

**Comment by millij** [comment]
@oshuk1 
Ordering of the Columns while writing is already available. It can be achieved by passing the headers order in a `List` to the `addSheet` API of `SpreadSheetWriter`. 

Please refer to the below code for usage

```java
SpreadsheetWriter ssWriter = new SpreadsheetWriter(<output_file_filepath>);

// Headers Order (note that you can pick only the headers you want to write here)
List<String> headers = Arrays.asList("ID", "Age", "Name", "Address");

// Add Sheet and pass the headers
ssWriter.addSheet(Employee.class, employees, headers);
ssWriter.write();

```
OR refer to this test case

https://github.com/millij/poi-object-mapper/blob/3f49d59dddfeca3446e288ba54e54a5bba357881/src/test/java/io/github/millij/poi/ss/writer/SpreadsheetWriterTest.java#L68

Hope this is what you're looking for.

**P.S.:** The description of the issue is quite misleading. 
It is supposed to be *Add support to provide the Order of the columns as part of the annotation metadata itself.*

**Comment by millij** [comment]
[`@SheetColumn`](https://github.com/millij/poi-object-mapper/blob/develop/src/main/java/io/github/millij/poi/ss/model/annotations/SheetColumn.java) annotation now (as of 3.0.0) supports `order` as an additional property.

This order value is used to order the Headers when writing to files.
