### ISSUE TITLE
Why is SpreadSheetWriter deprecated?

### ISSUE THREAD

**Issue by valakyr** [millij/poi-object-mapper#16]
Why is `SpreadSheetWriter` marked with `@deprecated`, despite being shown off in the `README.md`?
Is it truly being discontinued?

**Comment by millij** [comment]
Currently, the `SpreadSheetWriter` supports only `xssf`, i.e., `xlsx` writing.
Plan was to rewrite the `SpreadSheetWriter` into dedicated writers for `xls` and `xlsx`, similar to their respective readers. Hence the deprecation.

>> Is it truly being discontinued?
As explained above, the current `SpreadSheetWriter` implementation will be renamed to `XlsxWriter`.

**Comment by valakyr** [comment]
Thank you for clarifying.
