### ISSUE TITLE
How to read multi sheets every sheet into separated lists?

### ISSUE THREAD

**Issue by saraselim1** [millij/poi-object-mapper#17]
How to read multi sheets every sheet into separated lists?

**Comment by millij** [comment]
@saraselim1 
There is API to read by sheet no. 
You just need to pass the sheet number as third argument to `read` method.
Check below for usage..

```java
    ...
    final File xlsxFile = new File("<path_to_file>");
    final XlsReader reader = new XlsReader();
    List<Employee> employees = reader.read(Employee.class, xlsxFile, <sheet_no>);
    ...
```


As each sheet read is independent of other, each sheet can be mapped to different Class. Something like below..

```java
    ...
    final File xlsxFile = new File("<path_to_file>");
    final XlsReader reader = new XlsReader();
    
    // Sheet 1 is mapped to Teacher.class 
    List<Teacher> teachers = reader.read(Teacher.class, xlsxFile, 1);
    
    // Sheet 2 is mapped to Student.class
    List<Student> students = reader.read(Student.class, xlsxFile, 2);
    ...
```

Hope this helps. Will add this to Documentation.

**Comment by saraselim1** [comment]
Dear @millij 
What if I want to read get the sheet by its name, not number?

**Comment by millij** [comment]
@saraselim1
We don't have any API in `SpreadsheetReader` to read sheet by it's name. 
As it's a valid request, will take this up in the next release..
