### ISSUE TITLE
How to mapping LocalDate type?

### ISSUE THREAD

**Issue by baocaixue** [millij/poi-object-mapper#20]
excel cell value is like '2012-12-12 ',how to mapping pojo field? now, all can't mapping if pojo has LocalDate type field

**Comment by millij** [comment]
@baocaixue 
poi-object-mapper current version (1.0.0) doesn't support Date Fields (refer to enhancement #8 , which is yet to be completed).

Here is an alternate way (workaround) that I suggest till its completed and released.

Map the `Date` column to a **String field** and create an additional **get method** which reads the String date field and returns the required `LocalDate` object. Check below for the sample code..

```java
@Sheet
public class SampleDateMapping {

    @SheetColumn(value = "Date")
    private String dateStr;


    // Methods

    public LocalDate getLocalDate() {
        // Provide DateTimeFormatter if needed
        return LocalDate.parse(dateStr);
    }


    // Getters and Setters

    public String getDateStr() {
        return dateStr;
    }

    public void setDateStr(String dateStr) {
        this.dateStr = dateStr;
    }

}

```

Hope this helps.

**Comment by baocaixue** [comment]
Thanks.I got it!
