### ISSUE TITLE
Writer creates columns for methods that are not annotated with @SheetColumn

### ISSUE THREAD

**Issue by pbacz** [millij/poi-object-mapper#27]
`SpreadsheetWriter` creates columns for methods that are not annotated with `@SheetColumn`

Using `SpreadsheetWriterTest#test_write_xlsx_single_sheet` as an example:

Actual:
![single_sheet xlsx](https://user-images.githubusercontent.com/32469996/78029155-69f5ea00-7360-11ea-9451-96029bac3e2b.png)

Expected:
![single_sheet-expected xlsx](https://user-images.githubusercontent.com/32469996/78029168-6eba9e00-7360-11ea-9a67-4feeb864c752.png)

**Comment by pbacz** [comment]
@millij Please review.

**Comment by mnreddy7** [comment]
Any plans to fix this issue?

**Comment by pbacz** [comment]
@millij Closing this at it was not reviewed for too long. A new issue for version 3.0.0 is here: https://github.com/millij/poi-object-mapper/issues/58
