### ISSUE TITLE
Need support with POI 4.0.1

### ISSUE THREAD

**Issue by kumar-chandan-kc** [millij/poi-object-mapper#30]
Hi,

We are using jasper to generate reports and that either supports POI before 3.15 or 4.0.1 and above. Unfortunately, millij sits somewhere in between with version 3.17 being used.

There is no way out of this soup unless a jar is provided with support for higher versions of POI.

Could you help us with this requirement ?

**Comment by kumar-chandan-kc** [comment]
If you can give me access, I will make the changes, already working with our project

**Comment by millij** [comment]
@kumar-chandan-kc 
There was a [pre-release](https://github.com/millij/poi-object-mapper/releases/tag/2.0.0) with POI 4.0.1 Support.
https://github.com/millij/poi-object-mapper/releases/tag/2.0.0

Hope this helps

**Comment by kumar-chandan-kc** [comment]
works fine thank you. But unfortunately, we are facing a problem with jasper upgrade. Can I open a new issue with support for POI 3.10 ? Could be a big change, any leads ?

**Comment by millij** [comment]
@kumar-chandan-kc 
Added support for POI 3.10.1 in the below branch for your reference..
https://github.com/millij/poi-object-mapper/tree/poi-3.10-support

Please checkout and build from that branch. Below is the build command for your reference..
```
$ ./gradlew clean build
```

**Comment by kumar-chandan-kc** [comment]
Thanks a ton, it works for us 👌.

Appreciate the quick resolution. 👍
