### ISSUE TITLE
Push 2.0.0 version to maven central

### ISSUE THREAD

**Issue by kgopal551** [millij/poi-object-mapper#37]
apache poi 4.0.1 or 4.1.1 has security fixes. Could you please push poi-object-mapper:2.0.0 version maven central as release. So that those security issues will get addressed.

**Comment by millij** [comment]
poi-object-mapper:2.0.0 is now released to mavencentral

```
<dependency>
    <groupId>io.github.millij</groupId>
    <artifactId>poi-object-mapper</artifactId>
    <version>2.0.0</version>
</dependency>
```
