### ISSUE TITLE
How can read Date in java

### ISSUE THREAD

**Issue by ysferdgnn** [millij/poi-object-mapper#40]
How can I read dates ? I've tried Timestamp,util.Date,sql.Date. I can't parse dates

**Comment by millij** [comment]
@ysferdgnn 
The current versions doesn't have support for reading Dates directly - There is a ticket already available for this. #8 
However, you can do a simple workaround. Check this - #20

**Comment by ysferdgnn** [comment]
I fix it in my project. Thanks for your reply
