### ISSUE TITLE
How to stop reading from excel if found a particular string.

### ISSUE THREAD

**Issue by scarlet2131** [millij/poi-object-mapper#44]
Example: - In the excel at the end there are few calculation like total amount in the amount column and jst before that column in the last row it is written something like - totalAmount and then total amount in the next column of the same last row of the excel so , i want to stop reading from excel when i find this string "totalAmount".

**Comment by millij** [comment]
Apologies for the delay in replying to this..

The read API supports passing a custom `RowListener` implementation. This will have a callback for each row read. You can use this callback to validate the row and trigger the downstream operations. 
Example code below:

```
// Read
final XlsxReader reader = new XlsxReader();
reader.read(SomeBean.class, xlsxFile, new RowListener<>() {

    @Override
    public void row(int rowNum, SomeBean bean) {
        // TODO :: add validation here
    }

});
```
