### ISSUE TITLE
Same POJO for different files

### ISSUE THREAD

**Issue by iamsethi** [millij/poi-object-mapper#61]
I've one excel file column name - XYZ and another excel with column Name ABC . The column data is same in both the excels
Does the poi-object mapper supports same Sheet Column ? Otherwise i need to create 2 POJO as a workaround

```
 @SheetColumn("XYZ","ABC")
    private String test;
```

**Comment by millij** [comment]
@iamsethi 
The current API `(v3.0.0)` doesn't support multiple names (or aliases).

As for your case, I recommend creating two fields as opposed to creating 2 POJOs; 
Sample code below

```
public class Bean { 

    @SheetColumn("XYZ")
    private String test1;
    
    @SheetColumn("ABC")
    private String test2;
    

    public String getTest1() {
        return Objects.isNull(test1) ? test2 : test1;
    }

    public void setTest1(String test1) {
        this.test1 = test1;
    }

    public String getTest2() {
        return Objects.isNull(test2) ? test1 : test2;
    }

    public void setTest2(String test2) {
        this.test2 = test2;
    }

}
```
In some way, it is no different from creating an alias..

Hope this helps
